# Generated by Django 3.1.5 on 2021-01-19 17:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionChains',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('height', models.CharField(blank=True, max_length=500)),
                ('evolution_details', jsonfield.fields.JSONField(blank=True, null=True)),
                ('base_stats', jsonfield.fields.JSONField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
