# Generated by Django 3.1.5 on 2021-01-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpoke', '0002_evolutionchains_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionchains',
            name='id_pokemon',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
