# Generated by Django 3.1.5 on 2021-01-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpoke', '0003_evolutionchains_id_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionchains',
            name='base_stats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionchains',
            name='evolution_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
