# Generated by Django 3.1.5 on 2021-01-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpoke', '0004_auto_20210119_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionchains',
            name='evolves_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
